"""content pipeline schema

Revision ID: 0001_content_pipeline
Revises:
Create Date: 2026-08-31 23:52:58.311763+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql

from justnews_core.models import EMBEDDING_COSINE_OPS, EmbeddingVector

revision: str = "0001_content_pipeline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector must exist before any table declares a vector column.
    # Supabase ships it; enabling is idempotent.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_quota_usage",
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("usage_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("calls", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("provider", "usage_date"),
    )
    op.create_table(
        "editions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("language", sa.String(length=12), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "ingest_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trigger", sa.String(length=20), nullable=False),
        sa.Column("feeds_total", sa.Integer(), nullable=False),
        sa.Column("feeds_ok", sa.Integer(), nullable=False),
        sa.Column("feeds_not_modified", sa.Integer(), nullable=False),
        sa.Column("feeds_failed", sa.Integer(), nullable=False),
        sa.Column("entries_seen", sa.Integer(), nullable=False),
        sa.Column("articles_new", sa.Integer(), nullable=False),
        sa.Column("articles_duplicate", sa.Integer(), nullable=False),
        sa.Column("articles_clustered", sa.Integer(), nullable=False),
        sa.Column("gnews_calls", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ingest_runs_started",
        "ingest_runs",
        [sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("homepage_url", sa.Text(), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("language", sa.String(length=12), nullable=False),
        sa.Column("trust_score", sa.Float(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("trust_score between 0 and 1", name="ck_sources_trust_range"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "story_clusters",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("centroid", EmbeddingVector(384), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("article_count", sa.Integer(), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("language_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_story_clusters_last_seen", "story_clusters", ["last_seen_at"], unique=False)
    op.create_table(
        "topics",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("parent_id", sa.String(length=32), nullable=True),
        sa.Column("level", sa.SmallInteger(), nullable=False),
        sa.Column("path", postgresql.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("level between 1 and 5", name="ck_topics_level_range"),
        sa.ForeignKeyConstraint(["parent_id"], ["topics.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_topics_parent_id"), "topics", ["parent_id"], unique=False)
    op.create_index("ix_topics_path", "topics", ["path"], unique=False, postgresql_using="gin")
    op.create_table(
        "authors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "slug", name="uq_authors_source_slug"),
    )
    op.create_table(
        "feeds",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=12), nullable=False),
        sa.Column("topic_hint_id", sa.String(length=32), nullable=True),
        sa.Column("etag", sa.String(length=400), nullable=True),
        sa.Column("last_modified", sa.String(length=120), nullable=True),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_hint_id"], ["topics.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index(
        "ix_feeds_active_last_fetched", "feeds", ["active", "last_fetched_at"], unique=False
    )
    op.create_index(op.f("ix_feeds_source_id"), "feeds", ["source_id"], unique=False)
    op.create_table(
        "source_category_map",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("raw_category", sa.String(length=200), nullable=False),
        sa.Column("topic_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "raw_category", name="uq_source_category_map"),
    )
    op.create_index(
        op.f("ix_source_category_map_source_id"), "source_category_map", ["source_id"], unique=False
    )
    op.create_table(
        "topic_labels",
        sa.Column("topic_id", sa.String(length=32), nullable=False),
        sa.Column("language", sa.String(length=12), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("is_official", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("topic_id", "language"),
    )
    op.create_table(
        "articles",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("url_canonical", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("feed_id", sa.Integer(), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("story_cluster_id", sa.BigInteger(), nullable=True),
        sa.Column("language", sa.String(length=12), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("simhash", sa.BigInteger(), nullable=False),
        sa.Column("embedding", EmbeddingVector(384), nullable=True),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["authors.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["feed_id"], ["feeds.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["story_cluster_id"], ["story_clusters.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url_canonical"),
    )
    op.create_index(
        "ix_articles_lang_published",
        "articles",
        ["language", sa.literal_column("published_at DESC")],
        unique=False,
    )
    op.create_index(op.f("ix_articles_language"), "articles", ["language"], unique=False)
    op.create_index(
        "ix_articles_published_at_desc",
        "articles",
        [sa.literal_column("published_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_articles_search_vector",
        "articles",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("ix_articles_simhash", "articles", ["simhash"], unique=False)
    op.create_index(op.f("ix_articles_source_id"), "articles", ["source_id"], unique=False)
    op.create_index(
        op.f("ix_articles_story_cluster_id"), "articles", ["story_cluster_id"], unique=False
    )
    op.create_table(
        "article_topics",
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("topic_id", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("assigned_by", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "assigned_by in ('mapping', 'classifier', 'feed_hint', 'manual')",
            name="ck_article_topics_assigned_by",
        ),
        sa.CheckConstraint("confidence between 0 and 1", name="ck_article_topics_confidence"),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("article_id", "topic_id"),
    )
    op.create_index("ix_article_topics_topic", "article_topics", ["topic_id"], unique=False)
    # ### end Alembic commands ###

    op.create_index(
        "ix_articles_embedding_hnsw",
        "articles",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": EMBEDDING_COSINE_OPS},
    )


def downgrade() -> None:
    op.drop_index("ix_articles_embedding_hnsw", table_name="articles", postgresql_using="hnsw")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_article_topics_topic", table_name="article_topics")
    op.drop_table("article_topics")
    op.drop_index(op.f("ix_articles_story_cluster_id"), table_name="articles")
    op.drop_index(op.f("ix_articles_source_id"), table_name="articles")
    op.drop_index("ix_articles_simhash", table_name="articles")
    op.drop_index("ix_articles_search_vector", table_name="articles", postgresql_using="gin")
    op.drop_index("ix_articles_published_at_desc", table_name="articles")
    op.drop_index(op.f("ix_articles_language"), table_name="articles")
    op.drop_index("ix_articles_lang_published", table_name="articles")
    op.drop_table("articles")
    op.drop_table("topic_labels")
    op.drop_index(op.f("ix_source_category_map_source_id"), table_name="source_category_map")
    op.drop_table("source_category_map")
    op.drop_index(op.f("ix_feeds_source_id"), table_name="feeds")
    op.drop_index("ix_feeds_active_last_fetched", table_name="feeds")
    op.drop_table("feeds")
    op.drop_table("authors")
    op.drop_index("ix_topics_path", table_name="topics", postgresql_using="gin")
    op.drop_index(op.f("ix_topics_parent_id"), table_name="topics")
    op.drop_table("topics")
    op.drop_index("ix_story_clusters_last_seen", table_name="story_clusters")
    op.drop_table("story_clusters")
    op.drop_table("sources")
    op.drop_index("ix_ingest_runs_started", table_name="ingest_runs")
    op.drop_table("ingest_runs")
    op.drop_table("editions")
    op.drop_table("api_quota_usage")
    # ### end Alembic commands ###
