/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/analytics/dau": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily Active Users */
        get: operations["daily_active_users_v1_admin_analytics_dau_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/analytics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analytics Overview */
        get: operations["analytics_overview_v1_admin_analytics_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/analytics/retention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retention Cohorts */
        get: operations["retention_cohorts_v1_admin_analytics_retention_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/analytics/wau": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weekly Active Users */
        get: operations["weekly_active_users_v1_admin_analytics_wau_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/articles/removed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Removed Articles */
        get: operations["list_removed_articles_v1_admin_articles_removed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/articles/{article_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Article */
        post: operations["restore_article_v1_admin_articles__article_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/articles/{article_id}/takedown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Takedown Article */
        post: operations["takedown_article_v1_admin_articles__article_id__takedown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/articles/{article_id}/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Article Topics */
        get: operations["get_article_topics_v1_admin_articles__article_id__topics_get"];
        /** Set Article Topics */
        put: operations["set_article_topics_v1_admin_articles__article_id__topics_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Log */
        get: operations["list_audit_log_v1_admin_audit_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/feature-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Feature Flags */
        get: operations["list_feature_flags_v1_admin_feature_flags_get"];
        put?: never;
        /** Create Feature Flag */
        post: operations["create_feature_flag_v1_admin_feature_flags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/feature-flags/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Feature Flag */
        put: operations["set_feature_flag_v1_admin_feature_flags__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Feedback */
        get: operations["list_feedback_v1_admin_feedback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ingest-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ingest Runs */
        get: operations["list_ingest_runs_v1_admin_ingest_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Invites */
        get: operations["list_invites_v1_admin_invites_get"];
        put?: never;
        /** Create Invite */
        post: operations["create_invite_v1_admin_invites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Source Health */
        get: operations["list_source_health_v1_admin_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Topics */
        get: operations["list_topics_v1_admin_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{user_id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User Activity */
        get: operations["user_activity_v1_admin_users__user_id__activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set User Role */
        post: operations["set_user_role_v1_admin_users__user_id__role_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Articles */
        get: operations["list_articles_v1_articles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/articles/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Article */
        get: operations["get_article_v1_articles__article_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/blindspots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Blindspots
         * @description Stories being reported, but not in a language you read.
         *
         *     Ground News's Blindspot reframed around language rather than politics -
         *     and answerable here only because clustering is cross-lingual, so "the same
         *     story, elsewhere" is a thing this corpus can actually identify.
         */
        get: operations["blindspots_v1_blindspots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/editions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Editions
         * @description The regional views on offer - Google News' local-news equivalent.
         */
        get: operations["editions_v1_editions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exploration-deck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exploration Deck */
        get: operations["get_exploration_deck_v1_exploration_deck_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/explore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Explore
         * @description Latest news, ranked, no sign-in required.
         *
         *     Unlike /v1/feed this is not behind the beta gate or `require_user`: a
         *     signed-out visitor is exactly who explore is for, and their impressions
         *     are logged against their browsing session rather than a user id - or
         *     would be: this is the largest pre-consent observation surface in the
         *     app precisely because it is reachable with no sign-in and no beta
         *     access, so an anonymous visitor who has not consented generates zero
         *     impression rows here, not rows keyed on a throwaway session id.
         */
        get: operations["get_explore_v1_explore_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Feed */
        get: operations["get_feed_v1_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Feedback */
        post: operations["submit_feedback_v1_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/follows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Follows */
        get: operations["list_follows_v1_follows_get"];
        put?: never;
        /** Create Follow */
        post: operations["create_follow_v1_follows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/follows/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Source Follows */
        get: operations["list_source_follows_v1_follows_sources_get"];
        put?: never;
        /** Create Source Follow */
        post: operations["create_source_follow_v1_follows_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/follows/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Source Follow */
        delete: operations["delete_source_follow_v1_follows_sources__source_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/follows/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Follow */
        delete: operations["delete_follow_v1_follows__topic_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List History */
        get: operations["list_history_v1_history_get"];
        put?: never;
        /** Report Click */
        post: operations["report_click_v1_history_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invites/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeem Invite */
        post: operations["redeem_invite_v1_invites_redeem_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_v1_me_get"];
        put?: never;
        post?: never;
        /** Delete Me */
        delete: operations["delete_me_v1_me_delete"];
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_v1_me_patch"];
        trace?: never;
    };
    "/v1/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Me */
        get: operations["export_me_v1_me_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/reading-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reading Profile */
        get: operations["get_reading_profile_v1_me_reading_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/not-interested": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report Not Interested */
        post: operations["report_not_interested_v1_not_interested_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/not-interested/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Undo Not Interested
         * @description Reverses a not-interested mark. Records a new event rather than
         *     deleting the old one - see services.interactions.undo_not_interested.
         */
        delete: operations["undo_not_interested_v1_not_interested__article_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/saves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Saves */
        get: operations["list_saves_v1_saves_get"];
        put?: never;
        /** Create Save */
        post: operations["create_save_v1_saves_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/saves/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Save */
        delete: operations["delete_save_v1_saves__article_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Articles */
        get: operations["search_articles_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report Share */
        post: operations["report_share_v1_share_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sources
         * @description A discovery list for onboarding - the handful of sources publishing in
         *     one language a new reader is most likely to already recognise. Not a
         *     directory: no pagination, no filtering beyond language, bounded to
         *     service.SOURCE_DISCOVERY_LIMIT.
         */
        get: operations["sources_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_v1_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stories */
        get: operations["list_stories_v1_stories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stories/{story_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Story */
        get: operations["get_story_v1_stories__story_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Topics */
        get: operations["list_topics_v1_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trending
         * @description What readers are actually clicking, most-clicked first.
         *
         *     Ranked on behaviour rather than recency - a rail that repeated the feed's
         *     own ordering would be decoration. Built from the interaction log that
         *     already exists for Stage 6's benefit.
         */
        get: operations["trending_v1_trending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveUsersBucketOut */
        ActiveUsersBucketOut: {
            /** Active Users */
            active_users: number;
            /**
             * Bucket
             * Format: date-time
             */
            bucket: string;
        };
        /** ActivityEntryOut */
        ActivityEntryOut: {
            /** Article Id */
            article_id: number;
            /** Article Title */
            article_title: string;
            /** Event Type */
            event_type: string | null;
            /** Kind */
            kind: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Position */
            position: number | null;
            /** Ranking Policy */
            ranking_policy: string | null;
            /** Surface */
            surface: string;
        };
        /** AdminTopicOut */
        AdminTopicOut: {
            /** Article Count */
            article_count: number;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Level */
            level: number;
        };
        /** AnalyticsOverviewOut */
        AnalyticsOverviewOut: {
            /** Active Users */
            active_users: number;
            /** Ctr By Ranking Policy */
            ctr_by_ranking_policy: components["schemas"]["RankingPolicyCtrOut"][];
            /** Ctr By Surface */
            ctr_by_surface: components["schemas"]["SurfaceCtrOut"][];
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /** Top Articles */
            top_articles: components["schemas"]["TopArticleOut"][];
            /** Top Sources */
            top_sources: components["schemas"]["TopSourceOut"][];
        };
        /** ArticleOut */
        ArticleOut: {
            /** Id */
            id: number;
            /** Image Url */
            image_url: string | null;
            /** Language */
            language: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Snippet */
            snippet: string | null;
            /** Source Id */
            source_id: number;
            /** Source Name */
            source_name: string;
            /** Source Slug */
            source_slug: string;
            /** Story Cluster Id */
            story_cluster_id: number | null;
            /** Title */
            title: string;
            /**
             * Url
             * @description Canonical publisher URL. Always link out to this.
             */
            url: string;
        };
        /** ArticlePageOut */
        ArticlePageOut: {
            /** Items */
            items: components["schemas"]["ArticleOut"][];
            /**
             * Next Cursor
             * @description Opaque keyset cursor. Pass back as ?cursor=. Never an offset.
             */
            next_cursor?: string | null;
        };
        /** ArticleTopicOut */
        ArticleTopicOut: {
            /** Id */
            id: string;
            /** Is Primary */
            is_primary: boolean;
            /** Label */
            label: string;
        };
        /** ArticleTopicsIn */
        ArticleTopicsIn: {
            /** Primary Topic Id */
            primary_topic_id: string;
            /** Topic Ids */
            topic_ids: string[];
        };
        /** AuditLogEntryOut */
        AuditLogEntryOut: {
            /** Action */
            action: string;
            /** Admin User Id */
            admin_user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Details */
            details: {
                [key: string]: unknown;
            } | null;
            /** Id */
            id: number;
            /** Target Id */
            target_id: string | null;
            /** Target Type */
            target_type: string | null;
        };
        /**
         * BlindspotOut
         * @description A story with coverage, none of it in a language the reader reads.
         */
        BlindspotOut: {
            /** Coverage */
            coverage: components["schemas"]["LanguageCoverageOut"][];
            story: components["schemas"]["StoryOut"];
        };
        /** ClickIn */
        ClickIn: {
            /** Article Id */
            article_id: number;
            /** Impression Id */
            impression_id?: number | null;
            /** Position */
            position?: number | null;
            /** Surface */
            surface: string;
            /** Topic Id */
            topic_id?: string | null;
        };
        /** CohortWeekOut */
        CohortWeekOut: {
            /** Active Users */
            active_users: number;
            /** Week Offset */
            week_offset: number;
        };
        /** DeckCardOut */
        DeckCardOut: {
            article: components["schemas"]["ArticleOut"];
            /** Impression Id */
            impression_id: number | null;
            /** Topic Id */
            topic_id: string;
        };
        /** DeckOut */
        DeckOut: {
            /** Cards */
            cards: components["schemas"]["DeckCardOut"][];
        };
        /** EditionOut */
        EditionOut: {
            /** Code */
            code: string;
            /** Country */
            country: string | null;
            /** Is Default */
            is_default: boolean;
            /** Language */
            language: string;
            /** Name */
            name: string;
        };
        /** FeatureFlagCreateIn */
        FeatureFlagCreateIn: {
            /** Description */
            description: string;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /** Key */
            key: string;
        };
        /** FeatureFlagOut */
        FeatureFlagOut: {
            /** Description */
            description: string;
            /** Enabled */
            enabled: boolean;
            /** Key */
            key: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Updated By */
            updated_by: string | null;
        };
        /** FeatureFlagSetIn */
        FeatureFlagSetIn: {
            /** Enabled */
            enabled: boolean;
        };
        /** FeedItemOut */
        FeedItemOut: {
            article: components["schemas"]["ArticleOut"];
            /** Impression Id */
            impression_id: number | null;
        };
        /** FeedPageOut */
        FeedPageOut: {
            /** Items */
            items: components["schemas"]["FeedItemOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** FeedbackEntryOut */
        FeedbackEntryOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Locale */
            locale: string;
            /** Message */
            message: string;
            /** Path */
            path: string | null;
            /** User Id */
            user_id: string | null;
        };
        /** FeedbackIn */
        FeedbackIn: {
            /** Locale */
            locale: string;
            /** Message */
            message: string;
            /** Path */
            path?: string | null;
        };
        /** FeedbackOut */
        FeedbackOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
        };
        /** FollowIn */
        FollowIn: {
            /** Topic Id */
            topic_id: string;
        };
        /** FollowOut */
        FollowOut: {
            /**
             * Followed At
             * Format: date-time
             */
            followed_at: string;
            /** Topic Id */
            topic_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Environment */
            environment: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** HistoryOut */
        HistoryOut: {
            article: components["schemas"]["ArticleOut"];
            /**
             * Viewed At
             * Format: date-time
             */
            viewed_at: string;
        };
        /** HistoryPageOut */
        HistoryPageOut: {
            /** Items */
            items: components["schemas"]["HistoryOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** IngestRunOut */
        IngestRunOut: {
            /** Articles Clustered */
            articles_clustered: number;
            /** Articles Duplicate */
            articles_duplicate: number;
            /** Articles Enriched */
            articles_enriched: number;
            /** Articles New */
            articles_new: number;
            /** Deadline Reached */
            deadline_reached: boolean;
            /** Entries Seen */
            entries_seen: number;
            /** Error */
            error: string | null;
            /** Feeds Failed */
            feeds_failed: number;
            /** Feeds Not Modified */
            feeds_not_modified: number;
            /** Feeds Ok */
            feeds_ok: number;
            /** Feeds Total */
            feeds_total: number;
            /** Finished At */
            finished_at: string | null;
            /** Gnews Calls */
            gnews_calls: number;
            /** Id */
            id: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Trigger */
            trigger: string;
        };
        /** InviteCreateIn */
        InviteCreateIn: {
            /** Expires At */
            expires_at?: string | null;
            /**
             * Max Uses
             * @default 1
             */
            max_uses: number;
            /** Note */
            note?: string | null;
        };
        /** InviteOut */
        InviteOut: {
            /** Code */
            code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at: string | null;
            /** Max Uses */
            max_uses: number;
            /** Note */
            note: string | null;
            /** Uses */
            uses: number;
        };
        /** LanguageCoverageOut */
        LanguageCoverageOut: {
            /** Article Count */
            article_count: number;
            /** Language */
            language: string;
            /** Source Count */
            source_count: number;
        };
        /** LanguageMixOut */
        LanguageMixOut: {
            /** Count */
            count: number;
            /** Language */
            language: string;
        };
        /** MeExportOut */
        MeExportOut: {
            /** Follows */
            follows: {
                [key: string]: unknown;
            }[];
            /** History */
            history: {
                [key: string]: unknown;
            }[];
            /** Profile */
            profile: {
                [key: string]: unknown;
            };
            /** Saves */
            saves: {
                [key: string]: unknown;
            }[];
        };
        /** MeOut */
        MeOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Has Beta Access */
            has_beta_access: boolean;
            /** Id */
            id: string;
            /** Preferred Languages */
            preferred_languages: string[];
            /** Role */
            role: string;
        };
        /** MeUpdateIn */
        MeUpdateIn: {
            /** Preferred Languages */
            preferred_languages: string[];
        };
        /** NotInterestedIn */
        NotInterestedIn: {
            /** Article Id */
            article_id: number;
            /** Surface */
            surface: string;
        };
        /** RankingPolicyCtrOut */
        RankingPolicyCtrOut: {
            /** Clicks */
            clicks: number;
            /** Impressions */
            impressions: number;
            /** Ranking Policy */
            ranking_policy: string;
        };
        /** Readiness */
        Readiness: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unreachable" | "timeout";
            /** Detail */
            detail?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded";
        };
        /** ReadingProfileOut */
        ReadingProfileOut: {
            /** Languages */
            languages: components["schemas"]["LanguageMixOut"][];
            /** Sampled */
            sampled: number;
            /** Topics */
            topics: components["schemas"]["TopicMixOut"][];
        };
        /** RedeemIn */
        RedeemIn: {
            /** Code */
            code: string;
        };
        /** RetentionCohortOut */
        RetentionCohortOut: {
            /** Cohort Size */
            cohort_size: number;
            /**
             * Cohort Week
             * Format: date-time
             */
            cohort_week: string;
            /** Weeks */
            weeks: components["schemas"]["CohortWeekOut"][];
        };
        /** SaveIn */
        SaveIn: {
            /** Article Id */
            article_id: number;
        };
        /** SaveOut */
        SaveOut: {
            article: components["schemas"]["ArticleOut"];
            /**
             * Saved At
             * Format: date-time
             */
            saved_at: string;
        };
        /** SavePageOut */
        SavePageOut: {
            /** Items */
            items: components["schemas"]["SaveOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** SearchPageOut */
        SearchPageOut: {
            /** Items */
            items: components["schemas"]["ArticleOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** SetRoleIn */
        SetRoleIn: {
            /** Role */
            role: string;
        };
        /** ShareIn */
        ShareIn: {
            /** Article Id */
            article_id: number;
            /** Surface */
            surface: string;
            /** Topic Id */
            topic_id?: string | null;
        };
        /** SourceFollowIn */
        SourceFollowIn: {
            /** Source Id */
            source_id: number;
        };
        /** SourceFollowOut */
        SourceFollowOut: {
            /**
             * Followed At
             * Format: date-time
             */
            followed_at: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Source Id */
            source_id: number;
        };
        /** SourceHealthOut */
        SourceHealthOut: {
            /** Active */
            active: boolean;
            /** Article Count */
            article_count: number;
            /** Failing Feed Count */
            failing_feed_count: number;
            /** Feed Count */
            feed_count: number;
            /** Id */
            id: number;
            /** Language */
            language: string;
            /** Last Success At */
            last_success_at: string | null;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** SourceOut */
        SourceOut: {
            /** Homepage Url */
            homepage_url: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** StatsOut */
        StatsOut: {
            /** Articles */
            articles: number;
            /** Languages */
            languages: number;
            /** Sources */
            sources: number;
            /** Story Clusters */
            story_clusters: number;
        };
        /** StoryDetailOut */
        StoryDetailOut: {
            /** Articles */
            articles: components["schemas"]["ArticleOut"][];
            /**
             * Coverage
             * @default []
             */
            coverage: components["schemas"]["LanguageCoverageOut"][];
            story: components["schemas"]["StoryOut"];
        };
        /** StoryOut */
        StoryOut: {
            /** Article Count */
            article_count: number;
            /** Id */
            id: number;
            /** Language Count */
            language_count: number;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Source Count */
            source_count: number;
            /** Title */
            title: string;
        };
        /** SurfaceCtrOut */
        SurfaceCtrOut: {
            /** Clicks */
            clicks: number;
            /** Impressions */
            impressions: number;
            /** Surface */
            surface: string;
        };
        /** TakedownIn */
        TakedownIn: {
            /** Reason */
            reason: string;
        };
        /** TopArticleOut */
        TopArticleOut: {
            /** Id */
            id: number;
            /** Impressions */
            impressions: number;
            /** Language */
            language: string;
            /** Title */
            title: string;
        };
        /** TopSourceOut */
        TopSourceOut: {
            /** Id */
            id: number;
            /** Impressions */
            impressions: number;
            /** Name */
            name: string;
        };
        /** TopicMixOut */
        TopicMixOut: {
            /** Count */
            count: number;
            /** Label */
            label: string;
            /** Topic Id */
            topic_id: string;
        };
        /** TopicOut */
        TopicOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Slug */
            slug: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Invite Redeemed At */
            invite_redeemed_at: string | null;
            /** Preferred Languages */
            preferred_languages: string[];
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    daily_active_users_v1_admin_analytics_dau_get: {
        parameters: {
            query?: {
                window_days?: number;
                locale?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveUsersBucketOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analytics_overview_v1_admin_analytics_overview_get: {
        parameters: {
            query?: {
                window_days?: number;
                locale?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsOverviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retention_cohorts_v1_admin_analytics_retention_get: {
        parameters: {
            query?: {
                window_weeks?: number;
                max_weeks_since?: number;
                locale?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetentionCohortOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    weekly_active_users_v1_admin_analytics_wau_get: {
        parameters: {
            query?: {
                window_weeks?: number;
                locale?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveUsersBucketOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_removed_articles_v1_admin_articles_removed_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_article_v1_admin_articles__article_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    takedown_article_v1_admin_articles__article_id__takedown_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TakedownIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_article_topics_v1_admin_articles__article_id__topics_get: {
        parameters: {
            query?: {
                language?: string;
            };
            header?: never;
            path: {
                article_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleTopicOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_article_topics_v1_admin_articles__article_id__topics_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleTopicsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_log_v1_admin_audit_log_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_feature_flags_v1_admin_feature_flags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlagOut"][];
                };
            };
        };
    };
    create_feature_flag_v1_admin_feature_flags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeatureFlagCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlagOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_feature_flag_v1_admin_feature_flags__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeatureFlagSetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlagOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_feedback_v1_admin_feedback_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ingest_runs_v1_admin_ingest_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invites_v1_admin_invites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteOut"][];
                };
            };
        };
    };
    create_invite_v1_admin_invites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_source_health_v1_admin_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceHealthOut"][];
                };
            };
        };
    };
    list_topics_v1_admin_topics_get: {
        parameters: {
            query?: {
                parent?: string | null;
                q?: string | null;
                language?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTopicOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_v1_admin_users_get: {
        parameters: {
            query?: {
                role?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    user_activity_v1_admin_users__user_id__activity_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_user_role_v1_admin_users__user_id__role_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRoleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_articles_v1_articles_get: {
        parameters: {
            query?: {
                languages?: string | null;
                topic?: string | null;
                /** @description Publisher country - what makes an edition regional, not just a language. */
                country?: string | null;
                cursor?: string | null;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticlePageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_article_v1_articles__article_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    blindspots_v1_blindspots_get: {
        parameters: {
            query?: {
                /** @description The reader's languages. Stories covered in any of them are excluded. */
                languages?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlindspotOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    editions_v1_editions_get: {
        parameters: {
            query?: {
                languages?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exploration_deck_v1_exploration_deck_get: {
        parameters: {
            query?: {
                locale?: string;
                languages?: string | null;
            };
            header?: {
                "x-session-id"?: string | null;
                "x-analytics-consent"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_explore_v1_explore_get: {
        parameters: {
            query?: {
                languages?: string | null;
                /** @description UI locale the page was rendered in. */
                locale?: string;
                cursor?: string | null;
                page_size?: number;
            };
            header?: {
                "x-session-id"?: string | null;
                "x-analytics-consent"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feed_v1_feed_get: {
        parameters: {
            query?: {
                /** @description Overrides the reader's saved languages for this request. */
                languages?: string | null;
                /** @description UI locale the feed was rendered in. */
                locale?: string;
                cursor?: string | null;
                page_size?: number;
            };
            header?: {
                "x-session-id"?: string | null;
                "x-analytics-consent"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_v1_feedback_post: {
        parameters: {
            query?: never;
            header?: {
                "x-session-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_follows_v1_follows_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowOut"][];
                };
            };
        };
    };
    create_follow_v1_follows_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_source_follows_v1_follows_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceFollowOut"][];
                };
            };
        };
    };
    create_source_follow_v1_follows_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceFollowIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceFollowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_source_follow_v1_follows_sources__source_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_follow_v1_follows__topic_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_history_v1_history_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_click_v1_history_post: {
        parameters: {
            query?: never;
            header?: {
                "x-session-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClickIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redeem_invite_v1_invites_redeem_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    delete_me_v1_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_me_v1_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_me_v1_me_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeExportOut"];
                };
            };
        };
    };
    get_reading_profile_v1_me_reading_profile_get: {
        parameters: {
            query?: {
                language?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_not_interested_v1_not_interested_post: {
        parameters: {
            query?: never;
            header?: {
                "x-session-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotInterestedIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_not_interested_v1_not_interested__article_id__delete: {
        parameters: {
            query: {
                surface: string;
            };
            header?: {
                "x-session-id"?: string | null;
            };
            path: {
                article_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_saves_v1_saves_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavePageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_save_v1_saves_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_save_v1_saves__article_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_articles_v1_search_get: {
        parameters: {
            query: {
                q: string;
                languages?: string | null;
                cursor?: string | null;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_share_v1_share_post: {
        parameters: {
            query?: never;
            header?: {
                "x-session-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_v1_sources_get: {
        parameters: {
            query: {
                language: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_v1_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
        };
    };
    list_stories_v1_stories_get: {
        parameters: {
            query?: {
                limit?: number;
                min_sources?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_story_v1_stories__story_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_topics_v1_topics_get: {
        parameters: {
            query?: {
                language?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trending_v1_trending_get: {
        parameters: {
            query?: {
                languages?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
