"""record enrichment count and deadline outcome on ingest runs

Revision ID: 0002_ingest_run_outcome
Revises: 0001_content_pipeline
Create Date: 2026-09-01 00:40:07.628784+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0002_ingest_run_outcome"
down_revision: str | None = "0001_content_pipeline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # NOT NULL columns added to a populated table need a server default, or the
    # migration fails on every existing row. The defaults are dropped again
    # afterwards so the application stays the only thing that sets these.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ingest_runs",
        sa.Column("articles_enriched", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "ingest_runs",
        sa.Column("deadline_reached", sa.Boolean(), nullable=False, server_default="false"),
    )
    # ### end Alembic commands ###

    op.alter_column("ingest_runs", "articles_enriched", server_default=None)
    op.alter_column("ingest_runs", "deadline_reached", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ingest_runs", "deadline_reached")
    op.drop_column("ingest_runs", "articles_enriched")
    # ### end Alembic commands ###
